export ORACLE_BASE=/oracle
export ORACLE_HOME=$ORACLE_BASE/product/12.1.0/dbhome_1
export PATH=$PATH:$ORACLE_HOME/bin
rman target / <<EOF
RUN
{
CONFIGURE CONTROLFILE AUTOBACKUP OFF;
CONFIGURE DEVICE TYPE 'SBT_TAPE' BACKUP TYPE TO COMPRESSED BACKUPSET PARALLELISM 2;
CONFIGURE ARCHIVELOG BACKUP COPIES FOR DEVICE TYPE 'SBT_TAPE' TO 1;
CONFIGURE CHANNEL DEVICE TYPE 'SBT_TAPE' FORMAT '%d_%t_%s_%p' MAXPIECESIZE 50 G;
ALLOCATE CHANNEL T1 TYPE 'SBT_TAPE' PARMS 'ENV=(TDPO_OPTFILE=/usr/tivoli/tsm/client/oracle/bin64/tdpo.opt)' ;
ALLOCATE CHANNEL T2 TYPE 'SBT_TAPE' PARMS 'ENV=(TDPO_OPTFILE=/usr/tivoli/tsm/client/oracle/bin64/tdpo.opt)' ;
ALLOCATE CHANNEL T3 TYPE 'SBT_TAPE' PARMS 'ENV=(TDPO_OPTFILE=/usr/tivoli/tsm/client/oracle/bin64/tdpo.opt)' ;
ALLOCATE CHANNEL T4 TYPE 'SBT_TAPE' PARMS 'ENV=(TDPO_OPTFILE=/usr/tivoli/tsm/client/oracle/bin64/tdpo.opt)' ;
BACKUP FULL FILESPERSET 3 FORMAT 'DATABASE_%d_%t_%s_%p' (DATABASE);
RELEASE CHANNEL T1;
RELEASE CHANNEL T2;
RELEASE CHANNEL T3;
RELEASE CHANNEL T4;
}
SQL 'ALTER SYSTEM ARCHIVE LOG CURRENT';
RUN
{
ALLOCATE CHANNEL T5 TYPE 'SBT_TAPE' PARMS 'ENV=(TDPO_OPTFILE=/usr/tivoli/tsm/client/oracle/bin64/tdpo.opt)' ;
ALLOCATE CHANNEL T6 TYPE 'SBT_TAPE' PARMS 'ENV=(TDPO_OPTFILE=/usr/tivoli/tsm/client/oracle/bin64/tdpo.opt)' ;
ALLOCATE CHANNEL T7 TYPE 'SBT_TAPE' PARMS 'ENV=(TDPO_OPTFILE=/usr/tivoli/tsm/client/oracle/bin64/tdpo.opt)' ;
ALLOCATE CHANNEL T8 TYPE 'SBT_TAPE' PARMS 'ENV=(TDPO_OPTFILE=/usr/tivoli/tsm/client/oracle/bin64/tdpo.opt)' ;
BACKUP FILESPERSET 20 FORMAT 'ARCHIVELOG_%d_%t_%s_%p' ARCHIVELOG ALL DELETE INPUT;
RELEASE CHANNEL T5;
RELEASE CHANNEL T6;
RELEASE CHANNEL T7;
RELEASE CHANNEL T8;
ALLOCATE CHANNEL T9 TYPE 'SBT_TAPE' PARMS 'ENV=(TDPO_OPTFILE=/usr/tivoli/tsm/client/oracle/bin64/tdpo.opt)' ;
BACKUP CURRENT CONTROLFILE FOR STANDBY FORMAT 'STANDBY_CONTROLFILE_%d_%t_%s_%p';
RELEASE CHANNEL T9;
ALLOCATE CHANNEL T10 TYPE 'SBT_TAPE' PARMS 'ENV=(TDPO_OPTFILE=/usr/tivoli/tsm/client/oracle/bin64/tdpo.opt)' ;
BACKUP CURRENT CONTROLFILE FORMAT 'CONTROLFILE_%d_%t_%s_%p';
RELEASE CHANNEL T10;
ALLOCATE CHANNEL T11 TYPE 'SBT_TAPE' PARMS 'ENV=(TDPO_OPTFILE=/usr/tivoli/tsm/client/oracle/bin64/tdpo.opt)' ;
BACKUP SPFILE FORMAT 'SPFILE_%d_%t_%s_%p';
RELEASE CHANNEL T11;
}
EOF


















Full:
------

RUN {
ALLOCATE CHANNEL CH11 device type disk;
crosscheck archivelog all;
delete noprompt expired archivelog all;
RELEASE CHANNEL CH11;
ALLOCATE CHANNEL CH1 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH2 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH3 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH4 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH5 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH6 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH7 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH8 TYPE 'SBT_TAPE';
BACKUP INCREMENTAL LEVEL 0 DATABASE FORMAT '/FULL_%d_%t_%s_%p';
BACKUP FORMAT '/ARCHIVELOG_%d_%t_%s_%p' ARCHIVELOG ALL;
BACKUP CURRENT CONTROLFILE FORMAT '/CONTROLFILE_%d_%t_%s_%p';
DELETE NOPROMPT ARCHIVELOG ALL COMPLETED BEFORE "SYSDATE-3";
RELEASE CHANNEL CH1;
RELEASE CHANNEL CH2;
RELEASE CHANNEL CH3;
RELEASE CHANNEL CH4;
RELEASE CHANNEL CH5;
RELEASE CHANNEL CH6;
RELEASE CHANNEL CH7;
RELEASE CHANNEL CH8;
}



Inc:
-----

RUN {
ALLOCATE CHANNEL CH11 device type disk;
crosscheck archivelog all;
delete noprompt expired archivelog all;
RELEASE CHANNEL CH11;
ALLOCATE CHANNEL CH1 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH2 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH3 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH4 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH5 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH6 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH7 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH8 TYPE 'SBT_TAPE';
BACKUP INCREMENTAL LEVEL 1 DATABASE FORMAT '/INC_%d_%t_%s_%p';
BACKUP FORMAT '/ARCHIVELOG_%d_%t_%s_%p' ARCHIVELOG ALL;
BACKUP CURRENT CONTROLFILE FORMAT '/CONTROLFILE_%d_%t_%s_%p';
DELETE NOPROMPT ARCHIVELOG ALL COMPLETED BEFORE "SYSDATE-3";
RELEASE CHANNEL CH1;
RELEASE CHANNEL CH2;
RELEASE CHANNEL CH3;
RELEASE CHANNEL CH4;
RELEASE CHANNEL CH5;
RELEASE CHANNEL CH6;
RELEASE CHANNEL CH7;
RELEASE CHANNEL CH8;
}




Arc:
-----

RUN {
ALLOCATE CHANNEL CH11 device type disk;
crosscheck archivelog all;
delete noprompt expired archivelog all;
RELEASE CHANNEL CH11;
ALLOCATE CHANNEL CH1 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH2 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH3 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH4 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH5 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH6 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH7 TYPE 'SBT_TAPE';
ALLOCATE CHANNEL CH8 TYPE 'SBT_TAPE';
BACKUP FORMAT '/ARCHIVELOG_%d_%t_%s_%p' ARCHIVELOG ALL DELETE INPUT;
BACKUP CURRENT CONTROLFILE FORMAT '/CONTROLFILE_%d_%t_%s_%p';
RELEASE CHANNEL CH1;
RELEASE CHANNEL CH2;
RELEASE CHANNEL CH3;
RELEASE CHANNEL CH4;
RELEASE CHANNEL CH5;
RELEASE CHANNEL CH6;
RELEASE CHANNEL CH7;
RELEASE CHANNEL CH8;
}