export ORACLE_BASE=/oracle
export ORACLE_HOME=$ORACLE_BASE/product/12.1.0/dbhome_1
export PATH=$PATH:$ORACLE_HOME/bin
rman target / <<EOF
RUN
{
CROSSCHECK BACKUPSET;
CROSSCHECK ARCHIVELOG ALL;
DELETE NOPROMPT OBSOLETE DEVICE TYPE DISK;
ALLOCATE CHANNEL T1 TYPE DISK;
ALLOCATE CHANNEL T2 TYPE DISK;
ALLOCATE CHANNEL T3 TYPE DISK;
ALLOCATE CHANNEL T4 TYPE DISK;
ALLOCATE CHANNEL T5 TYPE DISK;
ALLOCATE CHANNEL T6 TYPE DISK;
ALLOCATE CHANNEL T7 TYPE DISK;
ALLOCATE CHANNEL T8 TYPE DISK;
BACKUP FULL FILESPERSET 5 FORMAT '/backup/files/DATABASE_%d_%t_%s_%p' (DATABASE);
SQL 'ALTER SYSTEM ARCHIVE LOG CURRENT';
BACKUP FILESPERSET 50 FORMAT '/backup/files/ARCHIVELOG_%d_%t_%s_%p' ARCHIVELOG ALL DELETE INPUT;
BACKUP CURRENT CONTROLFILE FOR STANDBY FORMAT '/backup/files/STANDBY_CONTROLFILE_%d_%t_%s_%p';
BACKUP CURRENT CONTROLFILE FORMAT '/backup/files/CONTROLFILE_%d_%t_%s_%p';
BACKUP SPFILE FORMAT '/backup/files/SPFILE_%d_%t_%s_%p';
RELEASE CHANNEL T1;
RELEASE CHANNEL T2;
RELEASE CHANNEL T3;
RELEASE CHANNEL T4;
RELEASE CHANNEL T5;
RELEASE CHANNEL T6;
RELEASE CHANNEL T7;
RELEASE CHANNEL T8;
}
EOF