CONFIGURE RETENTION POLICY TO RECOVERY WINDOW OF 60 DAYS;
CONFIGURE CONTROLFILE AUTOBACKUP ON;


alter system set remote_login_passwordfile = 'EXCLUSIVE' scope = spfile;


CREATE USER BACKUP IDENTIFIED BY rman10_2019 DEFAULT TABLESPACE SYSTEM TEMPORARY TABLESPACE TEMP PROFILE DEFAULT ACCOUNT UNLOCK;
GRANT CONNECT TO BACKUP;
GRANT RESOURCE TO BACKUP;
ALTER USER BACKUP DEFAULT ROLE ALL;
GRANT SYSDBA TO BACKUP;